name: user_rest_api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  args: ^2.3.1
  mysql_client: ^0.0.27

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  http: ^0.13.5
  mockito: ^5.3.2
  build_runner: ^2.2.0
